services:
  db:
    image: mariadb:10.5
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3306:3306
    networks:
      - freeso

  server:
    image: freeso
    volumes:
      - ./config.json:/app/config.json
      - ./game:/app/game
      - ./nfs:/app/nfs
      - ./vars:/app/vars
      - ./updates:/app/updates
    restart: on-failure
    depends_on:
      - db
    ports:
      - 35101:35101
      - 33101:33101
      - 34101:34101
      - 9000:9000
    networks:
      - freeso
      
  auth:
    image: freeso-auth
    volumes:
      - ./auth/.env:/app/.env
      - ./auth/database.db:/app/database.db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - freeso

volumes:
  db:
networks:
  freeso:
    driver: bridge
