services:
  db:
    image: mariadb:10.5
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_USER: fsoserver
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: fso
      MARIADB_ROOT_PASSWORD: wordpass
    ports:
      - 3306:3306
    networks:
      - freeso

  server:
    image: freeso
    volumes:
      - ./config.json:/app/config.json
      - ./game:/app/game
      - ./nfs:/app/nfs
      - ./vars:/app/vars
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 35:35
      - 34:34
      - 35101:35101
      - 33101:33101
      - 34101:34101
      - 9000:9000
    networks:
      - freeso
      
  auth:
    image: freeso-auth
    volumes:
      - ./auth/.env:/app/.env
      - ./auth/database.db:/app/database.db
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - freeso

volumes:
  db:
networks:
  freeso:
    driver: bridge
